# Generated by Django 3.2.7 on 2021-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_keyword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
