# Generated by Django 3.2.7 on 2021-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_keyword_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
            ],
        ),
    ]
